add: get offers from server using axios, error handle, loader
htmlacademy-react/170627-six-cities-10 pull request #11
Opened 2022-08-07 10:58 UTC by kskonovalov

2022-08-07 11:01 UTC, kskonovalov commented on project/src/api/api.ts
> +  api.interceptors.response.use(
В примере Угадай Мелодию под это дело сделан отдельный processErrorHandle:
https://github.com/htmlacademy-react/guess-melody-10/pull/7/commits/66b6febd62abb2ccb9a0c78ba4a1c98120f16936
https://github.com/htmlacademy-react/guess-melody-10/pull/7/commits/6fb40ddfc5d7f11b77cfbb7232ce3500672a594c

Я не понял почему, и оставил тут store.dispatch напрямую. У меня есть предположение, что это нужно (будет) для тестирования, но пока не знаю. Что ты думаешь?

2022-08-07 11:02 UTC, kskonovalov commented on project/src/components/ui/layout/layout.tsx
> +      {error !== null && <Error message={error}/>}
Здесь я заленился и решил просто вывести большую розовую плашку "error" сверху..

2022-08-07 11:03 UTC, kskonovalov commented on project/src/components/ux/loader.tsx
> +const Loader = () => (
Обожаю эти штуки https://loading.io/css/

2022-08-07 11:04 UTC, kskonovalov commented on project/src/pages/main/main.tsx
> +              {/* если убираю тут " || offersCount === 0", то после загрузки офферов _иногда_ мелькает "0 places to stay in Amsterdam"*/}
вот этот момент мне показался странным, но я думаю что это из-за того что dispatch могут вызываться не в том же порядке, в котором я их вызываю (я вызываю setLoading(false) сразу после setOffers())

2022-08-07 11:05 UTC, kskonovalov commented on project/src/store/api-actions.ts
> +    dispatch(offersLoading(false));
вот тут я делаю диспатч сначала loadOffers, потом offersLoading, но мне кажется что они не обязательно срабатывают в нужно порядке. Есть какой-то способ вызывать их последовательно?

2022-08-09 08:46 UTC, yurylavrukhin commented on project/src/api/api.ts
> +  api.interceptors.response.use(
отдельныф processErrorHandle — это просто функция которая вызывает store.dispatch дважды

2022-08-09 09:46 UTC, yurylavrukhin requested changes
✨  получилось великолепно!

2022-08-09 09:46 UTC, yurylavrukhin commented on project/src/components/ui/layout/layout.tsx
> +      {error !== null && <Error message={error}/>}
я не вижу логики исчезновения ошибки
добавь эту логику, пожалуйста
можешь по аналогии сделать с демкой https://github.com/htmlacademy-react/guess-melody-10/blob/6fb40ddfc5d7f11b77cfbb7232ce3500672a594c/project/src/store/api-actions.ts#L12

2022-08-09 13:37 UTC, merged