Module7 task3
htmlacademy-react/170627-six-cities-10 pull request #13
Opened 2022-08-11 10:35 UTC by kskonovalov

2022-08-12 03:15 UTC, yurylavrukhin requested changes
круто!

2022-08-12 03:15 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +import React, {useEffect, useState} from 'react';
при переходе на http://localhost:3001/offer/9999 (несуществующий оффер) бесконечно сыпятся красные уведомления-ошибки
поправь это, пожалуйста
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/26966797/184277700-6a1b150f-f657-4e3e-aab1-60119983a300.png">

2022-08-12 03:15 UTC, yurylavrukhin commented on project/src/pages/main/main.tsx
> +  // I tried to use useMemo here, but the app works faster without it
не нужно вносить изменений по этому комментарию 👌 

этого не может быть
оставь как есть, потом вынесем это в селекторы

2022-08-12 05:49 UTC, kskonovalov commented on project/src/pages/main/main.tsx
> +  // I tried to use useMemo here, but the app works faster without it
У меня в main.tsx фильтруются и сортируются офферы по выбранному городу и типу сортировки. Я обернул это в useMemo, но в таком случае переход между городами занимает около 2 секунд, в то время как без useMemo лаг ощутимо меньше, полсекунды или около того

`  const offersToDisplay = useMemo(() => (offers.filter((item) => item.city.name === city.title).sort((offer1, offer2) => {
    switch (sortBy) {
      case 'Popular':
        return 0; // default order;
      case 'PriceLowToHigh':
        return offer1.price - offer2.price;
      case 'PriceHighToLow':
        return offer2.price - offer1.price;
      case 'TopRatedFirst':
        return offer2.rating - offer1.rating;
      default:
        return 0;
    }
  })), [offers, city.title, sortBy]);`

и ещё с этим кодом появились warning:

> ImmutableStateInvariantMiddleware took 68ms, which is more than the warning threshold of 32ms. 
> If your state or actions are very large, you may want to disable the middleware as it might cause too much of a  slowdown in development mode. See https://redux-toolkit.js.org/api/getDefaultMiddleware for instructions.
> It is disabled in production builds, so you don't need to worry about that.

хотя вроде бы это не должно касаться RTK

2022-08-12 05:50 UTC, kskonovalov commented on project/src/pages/room/room.tsx
> +import React, {useEffect, useState} from 'react';
упс, я это проверял, но видимо до того как добавил недостающие зависимости в useEffect) поправил, спасибо

2022-08-13 15:58 UTC, yurylavrukhin commented on project/src/pages/main/main.tsx
> +  // I tried to use useMemo here, but the app works faster without it
интересно

2022-08-13 17:17 UTC, yurylavrukhin requested changes
я накинул немного штук которые нужно улучшить
думаю это будет полезно для твоего развития ☺️ 

поправь, пожалуйста, перформанс карты

проблема:
1. сейчас если сделать зум-аут (всю европу на карту поместить) 
2. попробовать сменить город — приложение лагает сильно на моём мощном компьютере

решение:
1. рисовать на карте маркеры только для выбранного города

2022-08-13 17:17 UTC, yurylavrukhin commented on project/src/pages/main/main.tsx
> +    if (loadingObj.offers in loading && !(loading[loadingObj.offers])) {
назови enum'ы, пожалуйста, с `PascalCase` в `project/src/const.ts`
https://www.typescriptlang.org/docs/handbook/enums.html

2022-08-13 17:17 UTC, yurylavrukhin commented on project/src/pages/main/main.tsx
> +      setOffersCount(offersToDisplay.length);
удали пожалуйста useEffect + useState для `offersCount` — это здесь излишне.

для вычисляемых значений, хранящихся в компоненте — стоит использовать хук useMemo

здесь вычисляемое значение — длина массива

то есть useEffect + useState будет заменён на → useMemo
это хорошая практика и так стоит делать ☺️ 

-----------------
конкретно здесь, можно и не мемоизировать, потому что взять длину массива — очень просто потому что это просто чтение свойства (оно не вычисляется при каждом прочтении)
https://stackoverflow.com/questions/32850662/time-complexity-of-javascripts-array-length

2022-08-13 17:17 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +  const [offerRequestSent, setOfferRequestSent] = useState(false);
от этой штуки стоит избавится
подробности в телеге ☺️

2022-08-13 18:19 UTC, kskonovalov commented on project/src/pages/main/main.tsx
> +    if (loadingObj.offers in loading && !(loading[loadingObj.offers])) {
Спасибо! 
Про маркеры, там ещё была проблема, что старые маркеры не удалялись, только добавлялись новые. Когда поменял компонент Map чтобы он брал только offersToDisplay, проблема стала очевидной) поправил это
И переименовал enum'ы

2022-08-13 18:19 UTC, kskonovalov commented on project/src/pages/main/main.tsx
> +      setOffersCount(offersToDisplay.length);
Круто, спасибо! Почистил код)

2022-08-13 18:20 UTC, kskonovalov commented on project/src/pages/room/room.tsx
> +  const [offerRequestSent, setOfferRequestSent] = useState(false);
И тут почистил код, спасибо большое за пояснения!

2022-08-16 03:13 UTC, merged