Module8 task1
htmlacademy-react/170627-six-cities-10 pull request #14
Opened 2022-08-16 20:18 UTC by kskonovalov

2022-08-16 20:21 UTC, kskonovalov commented
Юра, привет! В обновлении я добавил слайсы и обернул offersToDisplay в useMemo, проверил, лишний раз это не вычисляется. И тормоза при смене городов тоже пропали, возможно из-за того что я пофиксил карту. Можешь сказать, какие моменты ещё нужно проверять на оптимизацию и перерисовку?

2022-08-17 08:06 UTC, yurylavrukhin requested changes
good! 😎

2022-08-17 08:31 UTC, kskonovalov commented on project/src/components/ui/card/card.tsx
>  type CardProps = {
Проверил, круто! теперь да, при наведении на карту рендерит список и саму карту, но не ре-рендерит все остальные карточки

2022-08-17 08:34 UTC, kskonovalov commented on project/src/components/ui/card/card.tsx
>  type CardProps = {
Видимо, раньше причина re-render'а была в том, и это показывал react dev tools, "parent component changed"
оборачивание в memo видимо как-то говорит реакту, что если пропсы не поменялись, то и компонент перерисовывать не нужно. Думаю, что memo(компонент) должен так же работать и для компонентов без пропсов (неуправляемых?)

2022-08-24 02:46 UTC, yurylavrukhin approved these changes

2022-08-24 02:46 UTC, merged