Module9 task1
htmlacademy-react/170627-six-cities-10 pull request #16
Opened 2022-08-27 13:27 UTC by kskonovalov

2022-08-28 13:58 UTC, yurylavrukhin requested changes

2022-08-28 13:58 UTC, yurylavrukhin commented on project/src/components/private-route/private-route.test.tsx
> +  it('should render component for private route when user not authorized', () => {
`should render component for private route when user authorized`

2022-08-28 14:51 UTC, kskonovalov commented on project/src/components/private-route/private-route.test.tsx
> +  it('should render component for private route when user not authorized', () => {
точно, поправил, спасибо!

2022-08-29 07:44 UTC, yurylavrukhin approved these changes

2022-08-29 07:44 UTC, merged