add: main page layout, pages layout, fix: linter errors and warnings
htmlacademy-react/170627-six-cities-10 pull request #4
Opened 2022-07-10 18:39 UTC by kskonovalov

2022-07-12 00:28 UTC, yurylavrukhin requested changes
👍

2022-07-12 00:28 UTC, yurylavrukhin commented on project/src/pages/favorites-empty/favorites-empty.tsx
> +import React from 'react';
нам не нужна страничка favorites empty
удали этот файл и директорию в которой он лежит `favorites-empty`, пожалуйста

когда у пользователя нет favorites мы обработаем это условием внутри странички favorites

2022-07-12 00:28 UTC, yurylavrukhin commented on project/src/components/ux/card/card.tsx
> +          {/*                type="button">*/}
а этот кусочек кода закомментирован потому что он не нужен и его нужно удалить?

2022-07-12 00:30 UTC, yurylavrukhin requested changes
добавь пожалуйста страничку 404 🙏  она нам пригодится вот тут про неё написано в ТЗ
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/26966797/178381041-b675d487-b14c-47e9-bfef-0f9793e929c3.png">
https://up.htmlacademy.ru/react/10/project/six-cities#pages

2022-07-12 18:38 UTC, kskonovalov commented on project/src/components/ux/card/card.tsx
> +          {/*                type="button">*/}
На самом деле, там отдельный класс если карточка в закладках. Я вынес в отдельную строку, чтобы не потерять его, но сейчас вижу что отличается только одним классом, поэтому да, удалю этот фрагмент и добавлю класс просто кнопке :) спасибо!

2022-07-13 14:52 UTC, yurylavrukhin approved these changes
супер!

2022-07-13 14:53 UTC, merged