Module3 task1
htmlacademy-react/170627-six-cities-10 pull request #5
Opened 2022-07-13 22:27 UTC by kskonovalov

Added routes

2022-07-15 05:49 UTC, yurylavrukhin requested changes
супер! мне нравится страничка 404
- добавь пожалуйста ссылку на страничке 404 для чуваков чтобы они могли вернуться на главную страницу кликнув на эту ссылку :)

- давай придерживаться одной стилистики для названий файлов
`name-of-file.ts`
`PrivateRoute` и `Header` названы иначе

- **этот пункт можно игнорировать** 🙂 просто заметка для тебя 
пока оставляем как есть, в будущем нужно будет перенести isAuthorized в глобальный стор Redux 🙂 
<img width="1735" alt="image" src="https://user-images.githubusercontent.com/26966797/179159056-b2a56d0a-19c2-48ed-af2d-7d4cef34efc2.png">

2022-07-15 05:49 UTC, yurylavrukhin commented on project/src/components/ui/header/Header.tsx
> +              {(!isAuth && location.pathname !== AppRoute.Login) &&
старайся выносить вычисления из разметки, разметку в идеале должно быть легко читать

предлагаю создать переменную в теле компонента
`const isShowSignInButton = !isAuth && location.pathname !== AppRoute.Login`
и использовать её в разметке 

```
{isShowSignInButton &&
<li className="header__nav-item">
  <Link className="header__nav-link" to={AppRoute.Login}>
    <span className="header__signout">Sign in</span>
  </Link>
</li>}
```

то же самое касается сортировок, фильтраций и других вычислений, старайся держать разметку легкочитаемой

2022-07-15 05:49 UTC, yurylavrukhin commented on project/src/components/PrivateRoute.tsx
> +import React from 'react';
👍

2022-07-15 12:25 UTC, kskonovalov commented on project/src/components/ui/header/Header.tsx
> +              {(!isAuth && location.pathname !== AppRoute.Login) &&
Спасибо! Хорошее замечание) поправил это

2022-07-17 12:13 UTC, yurylavrukhin approved these changes
отлично получилось :)

2022-07-17 12:13 UTC, merged